 services:
  arttgcf:
    public: false
    build: .
    environment:
     PASSWORD: $PASSWORD
     MONGO_CON_STR: $MONGO_CON_STR
name: arttgcf
services:
  hello-world:
    labels:
      dev.okteto.com/private: "true"
    image: nginx
    ports:
      - 8080:8080
